# 1. ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hybrid-ai-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::198011705652:role/hybrid-ai-sa-role
---
# 2. Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-ai-service
  namespace: default
  labels:
    app: hybrid-ai
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hybrid-ai
  template:
    metadata:
      labels:
        app: hybrid-ai
    spec:
      serviceAccountName: hybrid-ai-sa
      containers:
        - name: ai-app
          image: 198011705652.dkr.ecr.ap-northeast-2.amazonaws.com/hybrid-service:ai-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: OLLAMA_URL
              # [수정됨] AWS EKS 내부의 ollama-service로 직접 연결
              value: "http://ollama-service:11434"
            - name: MILVUS_HOST
              value: "milvus-standalone"
            - name: S3_BUCKET_NAME
              value: "pbs-project-ai-data-dev-v1"
---
# 3. Service
apiVersion: v1
kind: Service
metadata:
  name: hybrid-ai-service
  namespace: default
  labels:
    argocd.argoproj.io/instance: pbs-ax-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: LoadBalancer
  selector:
    app: hybrid-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80