apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-ai-service
  namespace: default
  labels:
    app: hybrid-ai
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hybrid-ai
  template:
    metadata:
      labels:
        app: hybrid-ai
    spec:
      containers:
        - name: ai-app
          # [중요] 아까 논의한 대로 :ai-latest 태그를 사용하는 것이 좋습니다.
          image: 198011705652.dkr.ecr.ap-northeast-2.amazonaws.com/hybrid-service:ai-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hybrid-ai-service
  namespace: default
  labels:
    argocd.argoproj.io/instance: pbs-ax-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # 현재 LoadBalancer로 되어 있으나, 나중에 비용 절감을 위해 ClusterIP로 변경을 고려해보세요.
  type: LoadBalancer
  selector:
    app: hybrid-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80