apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-ai-service
  namespace: default
  labels:
    app: hybrid-ai
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hybrid-ai
  template:
    metadata:
      labels:
        app: hybrid-ai
    spec:
      containers:
        - name: ai-app
          image: 198011705652.dkr.ecr.ap-northeast-2.amazonaws.com/hybrid-service:ai-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # [HPA 작동을 위한 필수 리소스 설정]
          resources:
            requests:
              cpu: "100m"     # 평소 최소 0.1 코어 사용
              memory: "128Mi" # 최소 128MB 메모리 사용
            limits:
              cpu: "500m"     # 최대 0.5 코어까지만 허용
              memory: "512Mi" # 최대 512MB까지만 허용
          # [AI 엔진 및 S3 연동을 위한 환경 변수]
          env:
            - name: OLLAMA_URL
              value: "https://api.cloudreaminu.cloud" # 성공했던 온프레미스 주소
            - name: MILVUS_HOST
              value: "milvus-service"
            - name: S3_BUCKET_NAME
              value: "pbs-project-data-dev-v1"
            # AWS 권한 (미리 생성할 aws-secret 참조)
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: hybrid-ai-service
  namespace: default
  labels:
    argocd.argoproj.io/instance: pbs-ax-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: LoadBalancer
  selector:
    app: hybrid-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80