apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc # 위에서 만든 SC 이름과 일치해야 함
  resources:
    requests:
      storage: 20Gi