# 1. AI 중계 서비스 (Backend)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbs-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pbs-app
  template:
    metadata:
      labels:
        app: pbs-app
    spec:
      serviceAccountName: hybrid-ai-sa
      containers:
      - name: pbs-app
        # [통일] pbs-project-repo 창고의 ai-latest 사용 ⭐
        image: 198011705652.dkr.ecr.ap-northeast-2.amazonaws.com/pbs-project-repo:ai-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: MILVUS_ADDR
            value: "milvus-standalone.default.svc.cluster.local:19530"
          - name: OLLAMA_ADDR
            value: "http://api.cloudreaminu.cloud/ai"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
# 2. 웹 서비스 (Frontend)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbs-web-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pbs-web-service
  template:
    metadata:
      labels:
        app: pbs-web-service
    spec:
      containers:
      - name: web-container
        # [통일] pbs-project-repo 창고의 web-latest 사용 ⭐
        image: 198011705652.dkr.ecr.ap-northeast-2.amazonaws.com/pbs-project-repo:web-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80