apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pbs-web-ingress
  namespace: default
  annotations:
    # 1. SSL 인증서 (아까 확인된 ARN 그대로 사용)
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:198011705652:certificate/2ddb4d33-69cf-45e8-8278-e975b0469066
    
    # 2. 헬스체크 및 포트 설정
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: 200,404,301
    alb.ingress.kubernetes.io/target-type: ip
    
    # 3. 로드밸런서 타입 지정
    kubernetes.io/ingress.class: alb

spec:
  rules:
  - host: soldesk-group4-pbs-project.click
    http:
      paths:
      # [규칙 1] /api 로 시작하는 요청 -> AI 서버로 배달!
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hybrid-ai-service
            port:
              number: 80
              
      # [규칙 2] 나머지 모든 요청 -> 웹사이트로 배달!
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pbs-web-service
            port:
              number: 80