apiVersion: apps/v1
kind: Deployment
metadata:
  name: y-docs-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: y-docs-web
  template:
    metadata:
      labels:
        app: y-docs-web
    spec:
      containers:
      - name: web-container
        # 태그를 :latest에서 :web-latest로 변경했습니다.
        image: 198011705652.dkr.ecr.ap-northeast-2.amazonaws.com/pbs-project-repo:web-latest
        ports:
        - containerPort: 80