apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: pbs-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress # Ingress Gateway Pod의 레이블
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" # 모든 호스트 허용 (ELB 주소 및 도메인 접속 가능하게 변경)
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway # ArgoCD VirtualService가 참조하는 이름
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" # 모든 호스트 허용