apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: y-docs-vsvc
  namespace: default
spec:
  hosts:
  - "soldesk-group4-pbs-project.click"
  gateways:
  - istio-system/istio-gateway
  http:
  - route:
    - destination:
        host: pbs-web-service.default.svc.cluster.local
        port:
          number: 80