apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: y-docs-vsvc
  namespace: default
spec:
  hosts:
  - "soldesk-group4-pbs-project.click" # 도메인을 명시하여 충돌 방지
  gateways:
  - istio-system/istio-gateway
  http:
  - route:
    - destination:
        # 서비스 이름이 y-docs-web-service와 정확히 일치하는지 확인하세요.
        host: y-docs-web-service.default.svc.cluster.local
        port:
          number: 80