apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: y-docs-vsvc
  namespace: default  # y-docs-web-service가 있는 네임스페이스
spec:
  hosts:
  - "*"  # 또는 soldesk-group4-pbs-project.click
  gateways:
  - istio-system/istio-gateway # 위에서 만드신 Gateway 이름
  http:
  - route:
    - destination:
        host: y-docs-web-service # 서비스 이름과 정확히 일치해야 함
        port:
          number: 80