spec:
  hosts:
  - "soldesk-group4-pbs-project.click" # 메인 도메인 유지
  gateways:
  - istio-system/istio-gateway
  http:
  - route:
    - destination:
        host: y-docs-web-service.default.svc.cluster.local
        port:
          number: 80