apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: y-docs-vsvc
  namespace: default
spec:
  hosts:
  - "soldesk-group4-pbs-project.click" # 메인 도메인 담당
  gateways:
  - istio-system/istio-gateway # 네임스페이스 경로까지 명시
  http:
  - route:
    - destination:
        host: y-docs-web-service.default.svc.cluster.local # 서비스의 전체 주소(FQDN)
        port:
          number: 80