apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pbs-ax-platform
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    # 실제 Deployment, Service 파일들이 있는 폴더 경로로 수정
    path: manifests/eks/apps
    repoURL: https://github.com/minnnnnuuuu/PBS_2.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: hybrid-ai-service
    jsonPointers:
    - /spec/template/spec/containers/0/env
  - group: apps
    kind: Deployment
    name: pbs-app-deployment
    jsonPointers:
    - /spec/template/spec/containers/0/env