apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pbs-ax-platform
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/eks/apps
    repoURL: https://github.com/minnnnnuuuu/PBS_2.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: hybrid-ai-service
    jsonPointers:
    - /spec/template/spec/containers/0/env
    - /spec/replicas # [추가] HPA가 조절하는 파드 개수를 ArgoCD가 무시하도록 설정 ⭐
  - group: apps
    kind: Deployment
    name: pbs-web
    jsonPointers:
    - /spec/template/spec/containers/0/env
    - /spec/replicas # [추가] 웹 서비스도 동일하게 적용 ⭐